TARGET		= censusvisualizer
CONFIG	    += console debug
QT          += widgets
HEADERS	    += censusvisualizerheader.hpp
SOURCES     += censusvisualizerheader.cpp
HEADERS	    += censusvisualizerview.hpp
SOURCES     += censusvisualizerview.cpp
HEADERS	    += censusvisualizer.hpp
SOURCES     += censusvisualizer.cpp
SOURCES     += main.cpp
